export const SYNC_REVIEWS = "SYNC_REVIEWS";
export const SYNC_USER = "SYNC_USER";
export const SYNC_USERS = "SYNC_USERS";

export const SYNC_SHARED_PLACES_EE = "SYNC_SHARED_PLACES_EE";
export const SYNC_SHARED_PLACES_LV = "SYNC_SHARED_PLACES_LV";
export const SYNC_SHARED_PLACES_LT = "SYNC_SHARED_PLACES_LT";
export const SYNC_OWNED_PLACES = "SYNC_OWNED_PLACES";
export const SINGOUT_USER = "SINGOUT_USER";
